import { describe, test, expect } from "bun:test";
import { generateInjections } from "./codegen.js";
import type { TypeInfo } from "./transform.js";

describe("generateInjections", () => {
  test("generates namespace with Schema for a type", () => {
    const types: TypeInfo[] = [{ name: "Greeting", node: {} as any }];
    const schemas = new Map<string, object>([
      [
        "Greeting",
        {
          type: "object",
          properties: {
            message: { type: "string" },
          },
          required: ["message"],
          additionalProperties: false,
        },
      ],
    ]);

    const result = generateInjections(types, schemas);

    expect(result).toContain("namespace Greeting");
    expect(result).toContain("export const Schema: $$__thinkwell__acp__$$.SchemaProvider<Greeting>");
    expect(result).toContain("toJsonSchema: ()");
    expect(result).toContain('"type": "object"');
    expect(result).toContain('"message": {');
  });

  test("generates namespaces for multiple types", () => {
    const types: TypeInfo[] = [
      { name: "Greeting", node: {} as any },
      { name: "Farewell", node: {} as any },
    ];
    const schemas = new Map<string, object>([
      ["Greeting", { type: "object", properties: { message: { type: "string" } } }],
      ["Farewell", { type: "object", properties: { goodbye: { type: "string" } } }],
    ]);

    const result = generateInjections(types, schemas);

    expect(result).toContain("namespace Greeting");
    expect(result).toContain("namespace Farewell");
    expect(result).toContain("$$__thinkwell__acp__$$.SchemaProvider<Greeting>");
    expect(result).toContain("$$__thinkwell__acp__$$.SchemaProvider<Farewell>");
  });

  test("returns empty string for empty types array", () => {
    const result = generateInjections([], new Map());
    expect(result).toBe("");
  });

  test("skips types without schemas", () => {
    const types: TypeInfo[] = [{ name: "Missing", node: {} as any }];
    const schemas = new Map<string, object>();

    const result = generateInjections(types, schemas);

    expect(result).not.toContain("namespace Missing");
  });

  test("includes namespace import for @thinkwell/acp", () => {
    const types: TypeInfo[] = [{ name: "Test", node: {} as any }];
    const schemas = new Map<string, object>([["Test", { type: "string" }]]);

    const result = generateInjections(types, schemas);

    expect(result).toContain(
      'import type * as $$__thinkwell__acp__$$ from "@thinkwell/acp"'
    );
  });

  test("includes auto-generated comment", () => {
    const types: TypeInfo[] = [{ name: "Test", node: {} as any }];
    const schemas = new Map<string, object>([["Test", { type: "string" }]]);

    const result = generateInjections(types, schemas);

    expect(result).toContain("Auto-generated by @thinkwell/bun-plugin");
  });
});
