/**
 * Generates the virtual `__thinkwell_augmentations__.d.ts` content
 * from discovered @JSONSchema-marked types.
 *
 * This file is never written to disk — it is served to TypeScript
 * via a monkey-patched getScriptSnapshot().
 */

import type { MarkedType } from "./scanner";

/**
 * Generate a namespace merge declaration for a single marked type.
 *
 * Produces a declaration like:
 * ```
 * declare namespace Greeting {
 *   export const Schema: import("thinkwell").SchemaProvider<Greeting>;
 * }
 * ```
 *
 * The virtual file must be an ambient script (no top-level `export`), so
 * namespace declarations never use an `export` prefix. TypeScript merges
 * ambient namespaces with imported types regardless of the type's export status.
 */
function generateNamespaceDeclaration(type: MarkedType): string {
  return [
    `declare namespace ${type.name} {`,
    `  export const Schema: import("thinkwell").SchemaProvider<${type.name}>;`,
    `}`,
  ].join("\n");
}

/**
 * Generate the full virtual declaration file content from all marked types
 * across the project.
 *
 * @param typesByFile - Map from file path to the marked types found in that file.
 * @returns The complete `.d.ts` content for the virtual augmentations file.
 */
export function generateVirtualDeclarations(
  typesByFile: Map<string, MarkedType[]>,
): string {
  const declarations: string[] = [
    "// Auto-generated by @thinkwell/vscode-ts-plugin",
    "// This file is virtual and is never written to disk.",
    "",
  ];

  for (const [fileName, types] of typesByFile) {
    if (types.length === 0) continue;

    declarations.push(`// From ${fileName}`);
    for (const type of types) {
      declarations.push(generateNamespaceDeclaration(type));
      declarations.push("");
    }
  }

  return declarations.join("\n");
}
