/**
 * Generates the augmentation `.d.ts` content from discovered
 * @JSONSchema-marked types. The plugin writes this to disk at
 * `.thinkwell/augmentations.d.ts` in the project root.
 */

import type { MarkedType } from "./scanner";

/**
 * Generate a namespace merge declaration for a single marked type.
 *
 * Produces a declaration like:
 * ```
 * declare namespace Greeting {
 *   export const Schema: import("thinkwell").SchemaProvider<Greeting>;
 * }
 * ```
 *
 * Uses `import("thinkwell").SchemaProvider` rather than a locally-declared
 * interface so that TypeScript sees the *same* generic type that `think()`
 * expects. A local `SchemaProvider<T>` looks structurally identical but
 * `T` is a phantom parameter (unused in any property types), so TS can't
 * infer it across two different generic interfaces and falls back to
 * `unknown`.
 *
 * The `import()` type reference keeps the file as an ambient script
 * (no top-level import/export) so namespace declarations merge globally.
 */
function generateNamespaceDeclaration(type: MarkedType): string {
  return [
    `declare namespace ${type.name} {`,
    `  export const Schema: import("thinkwell").SchemaProvider<${type.name}>;`,
    `}`,
  ].join("\n");
}

/**
 * Generate the full virtual declaration file content from all marked types
 * across the project.
 *
 * @param typesByFile - Map from file path to the marked types found in that file.
 * @returns The complete `.d.ts` content for the virtual augmentations file.
 */
export function generateVirtualDeclarations(
  typesByFile: Map<string, MarkedType[]>,
): string {
  // Collect all types first — return empty string if there are none.
  // Writing an empty or header-only .d.ts causes TS 5.9's setDocument
  // to crash during updateGraphWorker.
  const allTypes: { fileName: string; type: MarkedType }[] = [];
  for (const [fileName, types] of typesByFile) {
    for (const type of types) {
      allTypes.push({ fileName, type });
    }
  }

  if (allTypes.length === 0) return "";

  const declarations: string[] = [
    "// Auto-generated by @thinkwell/vscode-ts-plugin — do not edit.",
    "",
  ];

  let currentFile = "";
  for (const { fileName, type } of allTypes) {
    if (fileName !== currentFile) {
      declarations.push(`// From ${fileName}`);
      currentFile = fileName;
    }
    declarations.push(generateNamespaceDeclaration(type));
    declarations.push("");
  }

  return declarations.join("\n");
}
