/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: pnpm generate:schemas
 * Source: src/generator.types.ts
 *
 * This file contains JSON schemas generated from TypeScript types
 * using ts-json-schema-generator. Re-run the generator if you
 * modify the source types.
 */

import type { SchemaProvider, JsonSchema } from "@dherman/sacp";
import type {
  Summary,
  AnalysisResult,
  Topic,
  Config,
  UserProfile,
  DocumentSection,
  DocumentAnalysis,
  TextPassage,
} from "./generator.types.js";

/**
 * Creates a SchemaProvider<T> from a raw JSON schema object.
 */
function schemaProvider<T>(schema: Record<string, unknown>): SchemaProvider<T> {
  return {
    toJsonSchema: () => schema as JsonSchema,
  };
}

/**
 * SchemaProvider for Summary type.
 * @generated
 */
export const SummarySchema: SchemaProvider<Summary> = schemaProvider<Summary>({
    "additionalProperties": false,
    "description": "A summary of content.",
    "properties": {
      "points": {
        "description": "Key points from the content",
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "title": {
        "description": "A brief title for the summary",
        "type": "string"
      },
      "wordCount": {
        "description": "Approximate word count of the original content",
        "minimum": 0,
        "type": "number"
      }
    },
    "required": [
      "title",
      "points",
      "wordCount"
    ],
    "type": "object"
  });

/**
 * SchemaProvider for AnalysisResult type.
 * @generated
 */
export const AnalysisResultSchema: SchemaProvider<AnalysisResult> = schemaProvider<AnalysisResult>({
    "additionalProperties": false,
    "description": "Result of sentiment analysis.",
    "properties": {
      "confidence": {
        "description": "Confidence score between 0 and 1",
        "maximum": 1,
        "minimum": 0,
        "type": "number"
      },
      "sentiment": {
        "description": "Overall sentiment of the content",
        "enum": [
          "positive",
          "negative",
          "neutral"
        ],
        "type": "string"
      },
      "topics": {
        "description": "Topics identified in the content",
        "items": {
          "additionalProperties": false,
          "description": "A topic with its relevance score.",
          "properties": {
            "name": {
              "description": "The topic name",
              "type": "string"
            },
            "relevance": {
              "description": "Relevance score between 0 and 1",
              "maximum": 1,
              "minimum": 0,
              "type": "number"
            }
          },
          "required": [
            "name",
            "relevance"
          ],
          "type": "object"
        },
        "type": "array"
      }
    },
    "required": [
      "sentiment",
      "confidence",
      "topics"
    ],
    "type": "object"
  });

/**
 * SchemaProvider for Topic type.
 * @generated
 */
export const TopicSchema: SchemaProvider<Topic> = schemaProvider<Topic>({
    "additionalProperties": false,
    "description": "A topic with its relevance score.",
    "properties": {
      "name": {
        "description": "The topic name",
        "type": "string"
      },
      "relevance": {
        "description": "Relevance score between 0 and 1",
        "maximum": 1,
        "minimum": 0,
        "type": "number"
      }
    },
    "required": [
      "name",
      "relevance"
    ],
    "type": "object"
  });

/**
 * SchemaProvider for Config type.
 * @generated
 */
export const ConfigSchema: SchemaProvider<Config> = schemaProvider<Config>({
    "additionalProperties": false,
    "description": "Configuration for LLM interactions.",
    "properties": {
      "maxTokens": {
        "description": "Maximum tokens to generate",
        "type": "number"
      },
      "systemPrompt": {
        "description": "System prompt to use",
        "type": "string"
      },
      "temperature": {
        "default": 0.7,
        "description": "Temperature setting (0-2)",
        "maximum": 2,
        "minimum": 0,
        "type": "number"
      }
    },
    "type": "object"
  });

/**
 * SchemaProvider for UserProfile type.
 * @generated
 */
export const UserProfileSchema: SchemaProvider<UserProfile> = schemaProvider<UserProfile>({
    "additionalProperties": false,
    "description": "A user profile with validated fields.",
    "properties": {
      "createdAt": {
        "description": "Account creation timestamp",
        "format": "date-time",
        "type": "string"
      },
      "email": {
        "description": "Email address",
        "format": "email",
        "type": "string"
      },
      "id": {
        "description": "Unique identifier",
        "format": "uuid",
        "type": "string"
      },
      "website": {
        "description": "Website URL",
        "format": "uri",
        "type": "string"
      }
    },
    "required": [
      "id",
      "email",
      "createdAt"
    ],
    "type": "object"
  });

/**
 * SchemaProvider for DocumentSection type.
 * @generated
 */
export const DocumentSectionSchema: SchemaProvider<DocumentSection> = schemaProvider<DocumentSection>({
    "additionalProperties": false,
    "description": "A section of a document with its sentiment analysis.",
    "properties": {
      "sentimentScore": {
        "description": "The sentiment score from the analysis tool",
        "type": "number"
      },
      "summary": {
        "description": "A brief summary of the section",
        "type": "string"
      },
      "title": {
        "description": "The section title",
        "type": "string"
      }
    },
    "required": [
      "title",
      "sentimentScore",
      "summary"
    ],
    "type": "object"
  });

/**
 * SchemaProvider for DocumentAnalysis type.
 * @generated
 */
export const DocumentAnalysisSchema: SchemaProvider<DocumentAnalysis> = schemaProvider<DocumentAnalysis>({
    "additionalProperties": false,
    "description": "Analysis of a document's sentiment and content.",
    "properties": {
      "overallTone": {
        "description": "The overall emotional tone of the document",
        "enum": [
          "positive",
          "negative",
          "mixed",
          "neutral"
        ],
        "type": "string"
      },
      "recommendation": {
        "description": "A recommendation based on the analysis",
        "type": "string"
      },
      "sections": {
        "description": "Analysis of each section",
        "items": {
          "additionalProperties": false,
          "description": "A section of a document with its sentiment analysis.",
          "properties": {
            "sentimentScore": {
              "description": "The sentiment score from the analysis tool",
              "type": "number"
            },
            "summary": {
              "description": "A brief summary of the section",
              "type": "string"
            },
            "title": {
              "description": "The section title",
              "type": "string"
            }
          },
          "required": [
            "title",
            "sentimentScore",
            "summary"
          ],
          "type": "object"
        },
        "type": "array"
      }
    },
    "required": [
      "overallTone",
      "sections",
      "recommendation"
    ],
    "type": "object"
  });

/**
 * SchemaProvider for TextPassage type.
 * @generated
 */
export const TextPassageSchema: SchemaProvider<TextPassage> = schemaProvider<TextPassage>({
    "additionalProperties": false,
    "description": "A text passage to analyze.",
    "properties": {
      "text": {
        "description": "The text passage to analyze",
        "type": "string"
      }
    },
    "required": [
      "text"
    ],
    "type": "object"
  });
