/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: @thinkwell/build-schema-providers
 * Source: generator.ts
 *
 * This file contains JSON schemas generated from TypeScript types
 * marked with @JSONSchema. Re-run the generator if you modify
 * the source types.
 */

import type { SchemaProvider, JsonSchema } from "@thinkwell/acp";
import type {
  Summary,
  AnalysisResult,
  Topic,
  DocumentSection,
  DocumentAnalysis,
  TextPassage,
} from "./generator.js";

/**
 * Creates a SchemaProvider<T> from a raw JSON schema object.
 */
function schemaProvider<T>(schema: Record<string, unknown>): SchemaProvider<T> {
  return {
    toJsonSchema: () => schema as JsonSchema,
  };
}

/**
 * SchemaProvider for Summary type.
 * @generated
 */
export const SummarySchema: SchemaProvider<Summary> = schemaProvider<Summary>({
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "description": "A brief title for the summary"
      },
      "points": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "description": "Key points from the content"
      },
      "wordCount": {
        "type": "number",
        "description": "Approximate word count of the original content",
        "minimum": 0
      }
    },
    "required": [
      "title",
      "points",
      "wordCount"
    ],
    "additionalProperties": false,
    "description": "A summary of content."
  });

/**
 * SchemaProvider for AnalysisResult type.
 * @generated
 */
export const AnalysisResultSchema: SchemaProvider<AnalysisResult> = schemaProvider<AnalysisResult>({
    "type": "object",
    "properties": {
      "sentiment": {
        "type": "string",
        "enum": [
          "positive",
          "negative",
          "neutral"
        ],
        "description": "Overall sentiment of the content"
      },
      "confidence": {
        "type": "number",
        "description": "Confidence score between 0 and 1",
        "minimum": 0,
        "maximum": 1
      },
      "topics": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "The topic name"
            },
            "relevance": {
              "type": "number",
              "description": "Relevance score between 0 and 1",
              "minimum": 0,
              "maximum": 1
            }
          },
          "required": [
            "name",
            "relevance"
          ],
          "additionalProperties": false,
          "description": "A topic with its relevance score."
        },
        "description": "Topics identified in the content"
      }
    },
    "required": [
      "sentiment",
      "confidence",
      "topics"
    ],
    "additionalProperties": false,
    "description": "Result of sentiment analysis."
  });

/**
 * SchemaProvider for Topic type.
 * @generated
 */
export const TopicSchema: SchemaProvider<Topic> = schemaProvider<Topic>({
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "The topic name"
      },
      "relevance": {
        "type": "number",
        "description": "Relevance score between 0 and 1",
        "minimum": 0,
        "maximum": 1
      }
    },
    "required": [
      "name",
      "relevance"
    ],
    "additionalProperties": false,
    "description": "A topic with its relevance score."
  });

/**
 * SchemaProvider for DocumentSection type.
 * @generated
 */
export const DocumentSectionSchema: SchemaProvider<DocumentSection> = schemaProvider<DocumentSection>({
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "description": "The section title"
      },
      "sentimentScore": {
        "type": "number",
        "description": "The sentiment score from the analysis tool"
      },
      "summary": {
        "type": "string",
        "description": "A brief summary of the section"
      }
    },
    "required": [
      "title",
      "sentimentScore",
      "summary"
    ],
    "additionalProperties": false,
    "description": "A section of a document with its sentiment analysis."
  });

/**
 * SchemaProvider for DocumentAnalysis type.
 * @generated
 */
export const DocumentAnalysisSchema: SchemaProvider<DocumentAnalysis> = schemaProvider<DocumentAnalysis>({
    "type": "object",
    "properties": {
      "overallTone": {
        "type": "string",
        "enum": [
          "positive",
          "negative",
          "mixed",
          "neutral"
        ],
        "description": "The overall emotional tone of the document"
      },
      "sections": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "title": {
              "type": "string",
              "description": "The section title"
            },
            "sentimentScore": {
              "type": "number",
              "description": "The sentiment score from the analysis tool"
            },
            "summary": {
              "type": "string",
              "description": "A brief summary of the section"
            }
          },
          "required": [
            "title",
            "sentimentScore",
            "summary"
          ],
          "additionalProperties": false,
          "description": "A section of a document with its sentiment analysis."
        },
        "description": "Analysis of each section"
      },
      "recommendation": {
        "type": "string",
        "description": "A recommendation based on the analysis"
      }
    },
    "required": [
      "overallTone",
      "sections",
      "recommendation"
    ],
    "additionalProperties": false,
    "description": "Analysis of a document's sentiment and content."
  });

/**
 * SchemaProvider for TextPassage type.
 * @generated
 */
export const TextPassageSchema: SchemaProvider<TextPassage> = schemaProvider<TextPassage>({
    "type": "object",
    "properties": {
      "text": {
        "type": "string",
        "description": "The text passage to analyze"
      }
    },
    "required": [
      "text"
    ],
    "additionalProperties": false,
    "description": "A text passage to analyze."
  });
