/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: @thinkwell/build-schema-providers
 * Source: greeting.ts
 *
 * This file contains JSON schemas generated from TypeScript types
 * marked with @JSONSchema. Re-run the generator if you modify
 * the source types.
 */

import type { SchemaProvider, JsonSchema } from "@thinkwell/acp";
import type {
  Greeting,
} from "./greeting.js";

/**
 * Creates a SchemaProvider<T> from a raw JSON schema object.
 */
function schemaProvider<T>(schema: Record<string, unknown>): SchemaProvider<T> {
  return {
    toJsonSchema: () => schema as JsonSchema,
  };
}

/**
 * SchemaProvider for Greeting type.
 * @generated
 */
export const GreetingSchema: SchemaProvider<Greeting> = schemaProvider<Greeting>({
    "type": "object",
    "properties": {
      "message": {
        "type": "string",
        "description": "The greeting message"
      }
    },
    "required": [
      "message"
    ],
    "additionalProperties": false,
    "description": "A friendly greeting."
  });
