/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * Generated by: @thinkwell/build-schema-providers
 * Source: unminify.ts
 *
 * This file contains JSON schemas generated from TypeScript types
 * marked with @JSONSchema. Re-run the generator if you modify
 * the source types.
 */

import type { SchemaProvider, JsonSchema } from "@thinkwell/acp";
import type {
  ModuleConversion,
  FunctionInfo,
  FunctionList,
  FunctionAnalysis,
  FunctionAnalysisBatch,
  RenamedCode,
} from "./unminify.js";

/**
 * Creates a SchemaProvider<T> from a raw JSON schema object.
 */
function schemaProvider<T>(schema: Record<string, unknown>): SchemaProvider<T> {
  return {
    toJsonSchema: () => schema as JsonSchema,
  };
}

/**
 * SchemaProvider for ModuleConversion type.
 * @generated
 */
export const ModuleConversionSchema: SchemaProvider<ModuleConversion> = schemaProvider<ModuleConversion>({
    "type": "object",
    "properties": {
      "code": {
        "type": "string",
        "description": "The converted ESM code with default export"
      },
      "exportedName": {
        "type": "string",
        "description": "The name of the main exported object/function"
      }
    },
    "required": [
      "code",
      "exportedName"
    ],
    "additionalProperties": false,
    "description": "Result of converting a UMD module to ESM."
  });

/**
 * SchemaProvider for FunctionInfo type.
 * @generated
 */
export const FunctionInfoSchema: SchemaProvider<FunctionInfo> = schemaProvider<FunctionInfo>({
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "Current function name (may be minified)"
      },
      "signature": {
        "type": "string",
        "description": "Function signature including parameters"
      },
      "lineNumber": {
        "type": "number",
        "description": "Approximate line number where the function is defined"
      }
    },
    "required": [
      "name",
      "signature",
      "lineNumber"
    ],
    "additionalProperties": false,
    "description": "Information about a function found in the code."
  });

/**
 * SchemaProvider for FunctionList type.
 * @generated
 */
export const FunctionListSchema: SchemaProvider<FunctionList> = schemaProvider<FunctionList>({
    "type": "object",
    "properties": {
      "functions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "Current function name (may be minified)"
            },
            "signature": {
              "type": "string",
              "description": "Function signature including parameters"
            },
            "lineNumber": {
              "type": "number",
              "description": "Approximate line number where the function is defined"
            }
          },
          "required": [
            "name",
            "signature",
            "lineNumber"
          ],
          "additionalProperties": false,
          "description": "Information about a function found in the code."
        },
        "description": "List of all top-level functions in the code"
      }
    },
    "required": [
      "functions"
    ],
    "additionalProperties": false,
    "description": "List of functions extracted from the code."
  });

/**
 * SchemaProvider for FunctionAnalysis type.
 * @generated
 */
export const FunctionAnalysisSchema: SchemaProvider<FunctionAnalysis> = schemaProvider<FunctionAnalysis>({
    "type": "object",
    "properties": {
      "originalName": {
        "type": "string",
        "description": "The original minified function name"
      },
      "suggestedName": {
        "type": "string",
        "description": "Suggested descriptive name (camelCase, no underscores unless conventional)"
      },
      "purpose": {
        "type": "string",
        "description": "Brief description of what the function does"
      },
      "confidence": {
        "type": "string",
        "enum": [
          "high",
          "medium",
          "low"
        ],
        "description": "Confidence level in the suggested name"
      }
    },
    "required": [
      "originalName",
      "suggestedName",
      "purpose",
      "confidence"
    ],
    "additionalProperties": false,
    "description": "Analysis result for a single function."
  });

/**
 * SchemaProvider for FunctionAnalysisBatch type.
 * @generated
 */
export const FunctionAnalysisBatchSchema: SchemaProvider<FunctionAnalysisBatch> = schemaProvider<FunctionAnalysisBatch>({
    "type": "object",
    "properties": {
      "analyses": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "originalName": {
              "type": "string",
              "description": "The original minified function name"
            },
            "suggestedName": {
              "type": "string",
              "description": "Suggested descriptive name (camelCase, no underscores unless conventional)"
            },
            "purpose": {
              "type": "string",
              "description": "Brief description of what the function does"
            },
            "confidence": {
              "type": "string",
              "enum": [
                "high",
                "medium",
                "low"
              ],
              "description": "Confidence level in the suggested name"
            }
          },
          "required": [
            "originalName",
            "suggestedName",
            "purpose",
            "confidence"
          ],
          "additionalProperties": false,
          "description": "Analysis result for a single function."
        },
        "description": "Array of function analyses"
      }
    },
    "required": [
      "analyses"
    ],
    "additionalProperties": false,
    "description": "Batch of function analyses."
  });

/**
 * SchemaProvider for RenamedCode type.
 * @generated
 */
export const RenamedCodeSchema: SchemaProvider<RenamedCode> = schemaProvider<RenamedCode>({
    "type": "object",
    "properties": {
      "code": {
        "type": "string",
        "description": "The code with all renames applied"
      },
      "renameCount": {
        "type": "number",
        "description": "Number of identifiers that were renamed"
      }
    },
    "required": [
      "code",
      "renameCount"
    ],
    "additionalProperties": false,
    "description": "Result of applying renames to code."
  });
