#!/usr/bin/env tsx
/**
 * Reads features.json and writes src/generated/features.ts into each package
 * that has a src/ directory.
 *
 * Usage:
 *   tsx scripts/generate-features.ts --mode=release   (values from features.json)
 *   tsx scripts/generate-features.ts --mode=debug     (all values true)
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = import.meta.dirname ?? dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// Parse --mode flag
const modeArg = process.argv.find((a) => a.startsWith("--mode="));
const mode = modeArg?.split("=")[1];
if (mode !== "release" && mode !== "debug") {
  console.error("Usage: generate-features.ts --mode=release|debug");
  process.exit(1);
}

// Read features.json
const configPath = join(ROOT, "features.json");
const config: { features: Record<string, boolean> } = JSON.parse(readFileSync(configPath, "utf-8"));
const featureNames = Object.keys(config.features);

// Build the feature values object
const values: Record<string, boolean> = {};
for (const name of featureNames) {
  values[name] = mode === "debug" ? true : config.features[name];
}

// Generate the TypeScript source
function generateSource(vals: Record<string, boolean>): string {
  const entries = Object.entries(vals)
    .map(([k, v]) => `  ${k}: ${v},`)
    .join("\n");

  const featureBlock = entries ? `\n${entries}\n` : "";

  return `// AUTO-GENERATED by scripts/generate-features.ts — do not edit
export const features = {${featureBlock}} as const;
`;
}

const source = generateSource(values);

// Write into every package that has a src/ directory
const packagesDir = join(ROOT, "packages");
for (const pkg of readdirSync(packagesDir)) {
  const srcDir = join(packagesDir, pkg, "src");
  if (!existsSync(srcDir)) continue;

  const genDir = join(srcDir, "generated");
  mkdirSync(genDir, { recursive: true });

  const outPath = join(genDir, "features.ts");
  writeFileSync(outPath, source, "utf-8");
}

console.log(`Generated features.ts (${mode} mode) for ${featureNames.length} feature(s)`);
