/**
 * Codegen script: reads .d.ts files from sibling packages and writes
 * a TypeScript module that exports them as string constants.
 *
 * Run with: npx tsx scripts/generate-bundled-types.ts
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = typeof import.meta.dirname === "string"
  ? import.meta.dirname
  : path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const PACKAGES_DIR = path.resolve(ROOT, "..");
const OUTPUT_FILE = path.join(ROOT, "src", "generated", "bundled-types.ts");

/**
 * Packages to bundle, in dependency order.
 * Each entry maps a module specifier to the package directory name and
 * the list of .d.ts files to include (relative to dist/).
 */
interface PackageSpec {
  /** npm module specifier (e.g., "thinkwell") */
  module: string;
  /** Directory name under packages/ */
  dir: string;
}

const PACKAGES: PackageSpec[] = [
  { module: "@thinkwell/protocol", dir: "protocol" },
  { module: "@thinkwell/acp", dir: "acp" },
  { module: "thinkwell", dir: "thinkwell" },
];

function collectDtsFiles(distDir: string): string[] {
  const files: string[] = [];

  function walk(dir: string, prefix: string) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        walk(path.join(dir, entry.name), rel);
      } else if (entry.name.endsWith(".d.ts")) {
        files.push(rel);
      }
    }
  }

  walk(distDir, "");
  return files.sort();
}

function main() {
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/generate-bundled-types.ts — do not edit",
    "//",
    "// Maps module specifier → relative file path → .d.ts content.",
    "",
    "export interface BundledPackage {",
    "  files: Record<string, string>;",
    "}",
    "",
    "export const BUNDLED_TYPES: Record<string, BundledPackage> = {",
  ];

  for (const pkg of PACKAGES) {
    const distDir = path.join(PACKAGES_DIR, pkg.dir, "dist");

    if (!fs.existsSync(distDir)) {
      console.error(`ERROR: dist/ not found for ${pkg.module} at ${distDir}`);
      console.error("Run 'pnpm -r run build' first to generate .d.ts files.");
      process.exit(1);
    }

    // Collect only the .d.ts files reachable from index.d.ts.
    // For simplicity, include all .d.ts files except those in cli/ subdirs
    // (which are internal CLI implementation details).
    const allFiles = collectDtsFiles(distDir);
    const files = allFiles.filter((f) => !f.startsWith("cli/"));

    lines.push(`  ${JSON.stringify(pkg.module)}: {`);
    lines.push(`    files: {`);

    for (const file of files) {
      const content = fs.readFileSync(path.join(distDir, file), "utf-8");
      // Strip sourceMappingURL comments
      const cleaned = content.replace(/\/\/# sourceMappingURL=.*$/gm, "").trimEnd();
      lines.push(`      ${JSON.stringify(file)}: ${JSON.stringify(cleaned)},`);
    }

    lines.push(`    },`);
    lines.push(`  },`);
  }

  lines.push("};");
  lines.push("");

  const output = lines.join("\n");
  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");

  // Summary
  let totalFiles = 0;
  for (const pkg of PACKAGES) {
    const distDir = path.join(PACKAGES_DIR, pkg.dir, "dist");
    const files = collectDtsFiles(distDir).filter((f) => !f.startsWith("cli/"));
    totalFiles += files.length;
    console.log(`  ${pkg.module}: ${files.length} .d.ts files`);
  }
  console.log(`Generated ${OUTPUT_FILE} (${totalFiles} files total)`);
}

main();
